version: "3"
services:
  cities-api-service:
    build: ./service
    environment:
      MONGO_URL: mongodb://root:pass@mongodb:27017/
    ports:
      - 80:80

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./mongodb-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongodb:27017/
